language: python
python:
  - "2.7"
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/pyflakes/pyflakes/tarball/master
  - pip install sphinx
  - sudo apt-get install libicu-dev
  - pip install pyicu
  - sudo apt-get install graphviz
  - sudo apt-get install hunspell
  - sudo apt-get install msort
  - bash utils/travis/install-locales.sh
script:
  - pep8 tests/ utils/ hunspell.py
  - pyflakes tests/ utils/ hunspell.py
  - sphinx-build -nW -b html doc doc/_build/html
  - sphinx-build -nW -b linkcheck doc doc/_build/html
  - python tests/doc-coverage.py
  - python tests/module_tests
